### ISSUE TITLE
Vauge error message on etcd errors

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena-docker-ipam-plugin#59]
Having a broken local etcd node (no connection to peers) results in HTTP 500 errors on etcd requests, which are then passed through as-is back to Docker, without any indication of them being etcd-related:

### `docker run --rm --network kontena-0 -it debian:jessie`
```
docker: Error response from daemon: Plugin.Activate: {"Error":"500 \"Internal Server Error\""}.
```

### `journalctl -u kontena-ipam`

```
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]: 2016-11-09 09:12:49 - Net::HTTPFatalError - 500 "Internal Server Error":
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/2.3.0/net/http/response.rb:120:in `error!'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/etcd-0.3.0/lib/etcd/client.rb:145:in `process_http_request'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/etcd-0.3.0/lib/etcd/client.rb:114:in `api_execute'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/etcd-0.3.0/lib/etcd/keys.rb:39:in `set'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /app/app/etcd_client.rb:80:in `set'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /app/lib/etcd_model.rb:236:in `mkdir'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /app/plugin.rb:26:in `ensure_models'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /app/plugin.rb:63:in `block in <class:IpamPlugin>'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:212:in `call'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]:         /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'
Nov 09 09:12:49 coreos-dev-01 kontena-ipam.sh[2537]: 127.0.0.1 - - [09/Nov/2016:09:12:49 +0000] "POST /Plugin.Activate HTTP/1.1" 500 41 7.0414
```

### `docker logs kontena-etcd`
```
2016-11-09 09:15:49.263607 E | etcdserver: publish error: etcdserver: request timed out
2016-11-09 09:15:49.769801 I | raft: bdcf7d2220de7f8e is starting a new election at term 38680
2016-11-09 09:15:49.773546 I | raft: bdcf7d2220de7f8e became candidate at term 38681
2016-11-09 09:15:49.773611 I | raft: bdcf7d2220de7f8e received vote from bdcf7d2220de7f8e at term 38681
2016-11-09 09:15:49.773651 I | raft: bdcf7d2220de7f8e [logterm: 38505, index: 1959795] sent vote request to 5dc32bbafbbf61d7 at term 38681
2016-11-09 09:15:51.070735 I | raft: bdcf7d2220de7f8e is starting a new election at term 38681
2016-11-09 09:15:51.074733 I | raft: bdcf7d2220de7f8e became candidate at term 38682
2016-11-09 09:15:51.074803 I | raft: bdcf7d2220de7f8e received vote from bdcf7d2220de7f8e at term 38682
2016-11-09 09:15:51.074852 I | raft: bdcf7d2220de7f8e [logterm: 38505, index: 1959795] sent vote request to 5dc32bbafbbf61d7 at term 38682
2016-11-09 09:15:51.191874 W | rafthttp: the connection to peer 5dc32bbafbbf61d7 is unhealthy
```

**Comment by SpComb** [comment]
With `kontena-etcd`, these kinds of errors will be `Kontena::Etcd::Error::RaftInternal` or `Kontena::Etcd::Error::ClientError` to provide slightly more error context.
